package sqlitestore_test

import (
	"context"
	"database/sql"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/MemaxLabs/memax-go-agent-sdk/toolkit/commandtools"
	transcriptsqlitestore "github.com/MemaxLabs/memax-go-agent-sdk/toolkit/commandtools/sqlitestore"
	_ "modernc.org/sqlite"
)

func TestOSSessionManagerRejectsRequestedIDAlreadyPersisted(t *testing.T) {
	store := newSQLiteTranscriptStore(t)
	if err := store.SaveCommandSession(context.Background(), commandtools.CommandSession{
		ID:        "persisted",
		SessionID: "session-1",
		Status:    commandtools.SessionExited,
		StartedAt: time.Now().UTC(),
		NextSeq:   1,
	}); err != nil {
		t.Fatalf("SaveCommandSession() error = %v", err)
	}

	manager, err := commandtools.NewOSSessionManager(t.TempDir(), commandtools.WithOSSessionManagerTranscriptStore(store))
	if err != nil {
		t.Fatalf("NewOSSessionManager returned error: %v", err)
	}
	if _, err := manager.StartCommand(context.Background(), commandtools.StartRequest{
		SessionID: "session-1",
		ID:        "persisted",
		Argv:      []string{filepath.Join(t.TempDir(), "missing-helper")},
	}); err != nil {
		assertCommandSessionError(t, err, commandtools.ErrCommandSessionAlreadyExists, "commandtools: command session persisted already exists")
	} else {
		t.Fatal("StartCommand duplicate persisted ID returned nil error, want ErrCommandSessionAlreadyExists")
	}
}

func TestOSSessionManagerSkipsPersistedAutoGeneratedIDs(t *testing.T) {
	sh := requireShell(t)
	store := newSQLiteTranscriptStore(t)
	if err := store.SaveCommandSession(context.Background(), commandtools.CommandSession{
		ID:        "cmd-1",
		SessionID: "session-1",
		Status:    commandtools.SessionExited,
		StartedAt: time.Now().UTC(),
		NextSeq:   1,
	}); err != nil {
		t.Fatalf("SaveCommandSession() error = %v", err)
	}

	manager, err := commandtools.NewOSSessionManager(t.TempDir(), commandtools.WithOSSessionManagerTranscriptStore(store))
	if err != nil {
		t.Fatalf("NewOSSessionManager returned error: %v", err)
	}
	started, err := manager.StartCommand(context.Background(), commandtools.StartRequest{
		SessionID: "session-1",
		Argv:      []string{sh, "-c", "printf 'ready\\n'; sleep 30"},
	})
	if err != nil {
		t.Fatalf("StartCommand returned error: %v", err)
	}
	defer func() {
		_, _ = manager.StopCommand(context.Background(), commandtools.StopRequest{SessionID: "session-1", ID: started.ID, Force: true})
	}()
	if started.ID != "cmd-2" {
		t.Fatalf("started.ID = %q, want auto-generated ID to skip persisted cmd-1", started.ID)
	}
}

func TestOSSessionManagerTranscriptStoreSupportsRestartReadAndListFallback(t *testing.T) {
	sh := requireShell(t)
	root := t.TempDir()
	appDir := filepath.Join(root, "app")
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		t.Fatalf("MkdirAll returned error: %v", err)
	}
	store := newSQLiteTranscriptStore(t)

	manager, err := commandtools.NewOSSessionManager(
		root,
		commandtools.WithOSSessionManagerTranscriptStore(store),
		commandtools.WithOSSessionManagerStopGrace(100*time.Millisecond),
	)
	if err != nil {
		t.Fatalf("NewOSSessionManager returned error: %v", err)
	}
	started, err := manager.StartCommand(context.Background(), commandtools.StartRequest{
		SessionID: "session-1",
		Argv:      []string{sh, "-c", "printf 'ready\\n'; sleep 30"},
		CWD:       "app",
	})
	if err != nil {
		t.Fatalf("StartCommand returned error: %v", err)
	}
	ready := waitForOutput(t, manager, commandtools.ReadRequest{SessionID: "session-1", ID: started.ID}, func(result commandtools.ReadResult) bool {
		return strings.Contains(joinChunkText(result.Chunks), "ready\n")
	})

	restarted, err := commandtools.NewOSSessionManager(root, commandtools.WithOSSessionManagerTranscriptStore(store))
	if err != nil {
		t.Fatalf("NewOSSessionManager(restarted) returned error: %v", err)
	}
	listed, err := restarted.ListCommands(context.Background(), commandtools.ListRequest{SessionID: "session-1", IncludeCompleted: true})
	if err != nil {
		t.Fatalf("ListCommands(restarted) returned error: %v", err)
	}
	if len(listed) != 1 || listed[0].ID != started.ID || listed[0].Status != commandtools.SessionRunning {
		t.Fatalf("listed = %#v, want persisted running session", listed)
	}

	persistedReady, err := restarted.ReadCommandOutput(context.Background(), commandtools.ReadRequest{SessionID: "session-1", ID: started.ID})
	if err != nil {
		t.Fatalf("ReadCommandOutput(restarted) error = %v", err)
	}
	if got := joinChunkText(persistedReady.Chunks); !strings.Contains(got, "ready\n") {
		t.Fatalf("persisted output = %q, want ready marker", got)
	}
	if persistedReady.Session.Status != commandtools.SessionRunning {
		t.Fatalf("persistedReady.Session.Status = %s, want running", persistedReady.Session.Status)
	}

	stopped, err := manager.StopCommand(context.Background(), commandtools.StopRequest{SessionID: "session-1", ID: started.ID})
	if err != nil {
		t.Fatalf("StopCommand returned error: %v", err)
	}
	if stopped.Status != commandtools.SessionStopped {
		t.Fatalf("stopped = %#v, want stopped session", stopped)
	}

	final := waitForOutput(t, restarted, commandtools.ReadRequest{
		SessionID: "session-1",
		ID:        started.ID,
		AfterSeq:  max(0, ready.NextSeq-1),
	}, func(result commandtools.ReadResult) bool {
		return result.Session.Status == commandtools.SessionStopped
	})
	if final.Session.ExitCode == nil {
		t.Fatalf("final = %#v, want persisted terminal snapshot with exit code", final)
	}
}

func TestOSSessionManagerTranscriptStorePersistsDurableDropSemantics(t *testing.T) {
	sh := requireShell(t)
	root := t.TempDir()
	store := newSQLiteTranscriptStore(t)

	manager, err := commandtools.NewOSSessionManager(
		root,
		commandtools.WithOSSessionManagerTranscriptStore(store),
		commandtools.WithOSSessionManagerMaxBufferedBytes(4),
	)
	if err != nil {
		t.Fatalf("NewOSSessionManager returned error: %v", err)
	}
	started, err := manager.StartCommand(context.Background(), commandtools.StartRequest{
		SessionID: "session-1",
		Argv:      []string{sh, "-c", "printf 'persisted-transcript\\n'; sleep 30"},
	})
	if err != nil {
		t.Fatalf("StartCommand returned error: %v", err)
	}
	defer func() {
		_, _ = manager.StopCommand(context.Background(), commandtools.StopRequest{SessionID: "session-1", ID: started.ID, Force: true})
	}()

	_ = waitForOutput(t, manager, commandtools.ReadRequest{SessionID: "session-1", ID: started.ID}, func(result commandtools.ReadResult) bool {
		return result.Session.DroppedChunks > 0
	})

	restarted, err := commandtools.NewOSSessionManager(root, commandtools.WithOSSessionManagerTranscriptStore(store))
	if err != nil {
		t.Fatalf("NewOSSessionManager(restarted) returned error: %v", err)
	}
	persisted, err := restarted.ReadCommandOutput(context.Background(), commandtools.ReadRequest{SessionID: "session-1", ID: started.ID})
	if err != nil {
		t.Fatalf("ReadCommandOutput(restarted) error = %v", err)
	}
	if got := joinChunkText(persisted.Chunks); !strings.Contains(got, "persisted-transcript\n") {
		t.Fatalf("persisted output = %q, want full durable transcript chunk", got)
	}
	if persisted.Session.DroppedChunks != 0 || persisted.Session.DroppedBytes != 0 {
		t.Fatalf("persisted.Session = %#v, want durable transcript snapshot without live-buffer drop counters", persisted.Session)
	}
}

func newSQLiteTranscriptStore(t *testing.T) commandtools.CommandTranscriptStore {
	t.Helper()

	db, err := sql.Open("sqlite", filepath.Join(t.TempDir(), "transcripts.db"))
	if err != nil {
		t.Fatalf("sql.Open() error = %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
	})
	store, err := transcriptsqlitestore.New(context.Background(), db)
	if err != nil {
		t.Fatalf("sqlitestore.New() error = %v", err)
	}
	return store
}

func requireShell(t *testing.T) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("shell-based transcript integration fixture is Unix-specific")
	}
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skipf("sh not available: %v", err)
	}
	return sh
}

func waitForOutput(t *testing.T, manager *commandtools.OSSessionManager, req commandtools.ReadRequest, ok func(commandtools.ReadResult) bool) commandtools.ReadResult {
	t.Helper()
	deadline := time.Now().Add(5 * time.Second)
	var last commandtools.ReadResult
	for time.Now().Before(deadline) {
		result, err := manager.ReadCommandOutput(context.Background(), req)
		if err != nil {
			t.Fatalf("ReadCommandOutput returned error: %v", err)
		}
		last = result
		if ok(result) {
			return result
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("timed out waiting for output; last=%#v", last)
	return commandtools.ReadResult{}
}

func joinChunkText(chunks []commandtools.OutputChunk) string {
	var b strings.Builder
	for _, chunk := range chunks {
		b.WriteString(chunk.Text)
	}
	return b.String()
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func assertCommandSessionError(t *testing.T, err error, target error, want string) {
	t.Helper()
	if !errors.Is(err, target) {
		t.Fatalf("error = %v, want %v", err, target)
	}
	if got := err.Error(); got != want {
		t.Fatalf("error string = %q, want %q", got, want)
	}
}
